version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketr-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
      - meilisearch
      - minio
    networks:
      - ticketr

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - ticketr

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ticketr}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-ticketr}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticketr

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ticketr

  meilisearch:
    image: getmeili/meilisearch:v1.7
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    networks:
      - ticketr

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minio}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minio123}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - ticketr

  horizon:
    image: ticketr-app
    restart: unless-stopped
    command: php artisan horizon
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
      - minio
    networks:
      - ticketr

  websocket-server:
    image: ticketr-app
    restart: unless-stopped
    command: php artisan websockets:serve
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - minio
    networks:
      - ticketr

volumes:
  mysql_data:
  minio_data:

networks:
  ticketr:
    driver: bridge
