<?php

return [
    'defaults' => [
        'statuses' => [
            [
                'name' => 'Open',
                'slug' => 'open',
                'description' => 'Newly created ticket awaiting triage.',
                'sort_order' => 10,
                'is_default' => true,
                'first_response_minutes' => 60,
                'resolution_minutes' => 480,
            ],
            [
                'name' => 'Pending',
                'slug' => 'pending',
                'description' => 'Waiting on customer response or clarification.',
                'sort_order' => 20,
                'first_response_minutes' => 120,
                'resolution_minutes' => 720,
            ],
            [
                'name' => 'Resolved',
                'slug' => 'resolved',
                'description' => 'Solution provided and awaiting confirmation.',
                'sort_order' => 30,
                'first_response_minutes' => null,
                'resolution_minutes' => null,
            ],
            [
                'name' => 'Closed',
                'slug' => 'closed',
                'description' => 'Ticket closed after confirmation or timeout.',
                'sort_order' => 40,
                'first_response_minutes' => null,
                'resolution_minutes' => null,
            ],
            [
                'name' => 'Archived',
                'slug' => 'archived',
                'description' => 'Archived for long term retention.',
                'sort_order' => 50,
                'first_response_minutes' => null,
                'resolution_minutes' => null,
            ],
        ],
        'priorities' => [
            [
                'name' => 'Low',
                'slug' => 'low',
                'color' => '#22C55E',
                'sort_order' => 10,
                'is_default' => false,
                'first_response_minutes' => 480,
                'resolution_minutes' => 2880,
            ],
            [
                'name' => 'Normal',
                'slug' => 'normal',
                'color' => '#3B82F6',
                'sort_order' => 20,
                'is_default' => true,
                'first_response_minutes' => 240,
                'resolution_minutes' => 1440,
            ],
            [
                'name' => 'High',
                'slug' => 'high',
                'color' => '#F97316',
                'sort_order' => 30,
                'is_default' => false,
                'first_response_minutes' => 120,
                'resolution_minutes' => 720,
            ],
            [
                'name' => 'Urgent',
                'slug' => 'urgent',
                'color' => '#EF4444',
                'sort_order' => 40,
                'is_default' => false,
                'first_response_minutes' => 30,
                'resolution_minutes' => 240,
            ],
        ],
        'transitions' => [
            ['from' => 'open', 'to' => 'pending'],
            ['from' => 'open', 'to' => 'resolved'],
            ['from' => 'open', 'to' => 'closed', 'requires_comment' => true],
            ['from' => 'pending', 'to' => 'open'],
            ['from' => 'pending', 'to' => 'resolved'],
            ['from' => 'pending', 'to' => 'closed', 'requires_comment' => true],
            ['from' => 'resolved', 'to' => 'closed'],
            ['from' => 'resolved', 'to' => 'open', 'requires_comment' => true],
            ['from' => 'closed', 'to' => 'archived'],
        ],
    ],
];
